//global variable
let dragonNames = [];
let dragonNamesSortedLengthwise = [];
let namesSpaceBefore = [];
let namesSpaceAfter = [];
let namesSpaceBoth = [];

//reads the csv with dragon names when the page is loaded. Code from some stackoverflow post
$(document).ready(function() {
    $.ajax({
        type: "GET",
        url: "dragon_names.csv",
        dataType: "text",
        success: function(data) {
            dragonNames = getDragonNames(data);
            document.getElementById("mostRecent").innerText = "Most recent dragon added: "+dragonNames[dragonNames.length-1];
            dragonNamesSortedLengthwise = sortArrayByItemLength(dragonNames);
            namesSpaceBefore = addSpaces(dragonNamesSortedLengthwise,"before");
            namesSpaceAfter = addSpaces(dragonNamesSortedLengthwise,"after");
            namesSpaceBoth = addSpaces(dragonNamesSortedLengthwise,"both");
        }
     });
    
});

//adds spaces to each word in input array
function addSpaces(input,where){
    inputLength = input.length;
    output = [];
    if (where=="before"){
        for (let i=0;i<inputLength;i++){
            output.push(" "+input[i]);
        }
    }
    else if (where=="after"){
      for (let i=0;i<inputLength;i++){
            output.push(input[i]+" ");
        }  
    }
    else if (where=="both"){
        for (let i=0;i<inputLength;i++){
            output.push(" "+input[i]+" ");
        }
    }
    return output;
}

// Escape regex special characters (chatgpt generated)
function escapeRegExp(str) {
    return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// Highlights all words using one color. Function generated by ChatGPT
function replaceWithFormattedDOMMulti(input, words, color = "firebrick") {
    const container = document.createElement("span");

    if (!words || words.length === 0) {
        container.textContent = input;
        return container;
    }

    // Build /(word1|word2|word3)/gi
    const pattern = words.map(escapeRegExp).join("|");
    const regex = new RegExp(pattern, "gi");

    let lastIndex = 0;
    let match;

    while ((match = regex.exec(input)) !== null) {
        // Append text before the match
        container.appendChild(
            document.createTextNode(input.slice(lastIndex, match.index))
        );

        // Append highlighted match
        const boldNode = document.createElement("b");
        boldNode.textContent = match[0];
        boldNode.style.color = color;
        container.appendChild(boldNode);

        lastIndex = regex.lastIndex;
    }

    // Append remaining text
    container.appendChild(document.createTextNode(input.slice(lastIndex)));

    return container;
}

//highlights all targeted words, displays them
function analyzeTheInput() {
    const input = document.getElementById("inputfield").value;
    const output = document.getElementById("outputText");
    
    output.innerHTML = "";
    
    if (document.getElementById('noSpace').checked) {
        output.appendChild(replaceWithFormattedDOMMulti(input, dragonNamesSortedLengthwise));
    }
    else if (document.getElementById('spaceBefore').checked) {
        output.appendChild(replaceWithFormattedDOMMulti(input, namesSpaceBefore));
    }
    else if (document.getElementById('spaceAfter').checked) {
        output.appendChild(replaceWithFormattedDOMMulti(input, namesSpaceAfter));
    }
    else if (document.getElementById('spaceBoth').checked) {
        output.appendChild(replaceWithFormattedDOMMulti(input, namesSpaceBoth));
    }
    else{
      output.innerHTML = "Something has gone very, very wrong. You should be afraid...";  
    }
    
}

function getDragonNames(allText) {
    return allText
        .split(/\r\n|\n/)        // split into lines
        .filter(line => line.trim() !== "") // skip empty lines
        .flatMap(line => line.split(","));  // split each line into names
}

//sorts the array by length (longest first) From stack overflow comment
function sortArrayByItemLength(inputArray){
    return inputArray.sort((a, b) => b.length - a.length || a.localeCompare(b));
}